version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # You can also use the pre-built image from Docker Hub:
    # image: flintsh/flare:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://flare:flarepassword@postgres:5432/flare?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
    volumes:
      - uploads:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=flare
      - POSTGRES_PASSWORD=flarepassword
      - POSTGRES_DB=flare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  uploads: 