#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format staged files
echo "🔍 Formatting staged files..."
bunx lint-staged

# Stage the formatted files
git add .

# Run a lint check
echo "🧹 Running lint check..."
bun lint || (
    echo "❌ Lint check failed. Please fix the issues and commit again."
    exit 1
)

# Run a final format check
echo "✨ Running final format check..."
bunx prettier --check "**/*.{ts,tsx,js,jsx,json,md}" || (
    echo "❌ Formatting check failed. Please commit again."
    exit 1
)
