name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bun install --frozen-lockfile

      - name: Type Check
        run: bunx tsc --noEmit

      - name: Lint
        run: bun run lint

      - name: Check formatting
        run: bunx prettier --check "**/*.{ts,tsx,js,jsx,json,md}"