name: Dev Release

on:
  push:
    branches: [ dev ]

jobs:
  create-dev-release:
    name: Create Dev Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/flintsh/flare:dev
            flintsh/flare:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Delete existing dev release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete the release if it exists (ignore error if it doesn't)
          gh release delete development --yes || true
          # Delete the remote tag
          git push origin :refs/tags/development || true
          # Delete the local tag if it exists
          git tag -d development || true

      - name: Create Dev Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: |
            🚧 Latest development build from dev branch

            Get the Docker image from GitHub Container Registry:
            ```bash
            docker pull ghcr.io/flintsh/flare:dev
            ```

            Or from Docker Hub:
            ```bash
            docker pull flintsh/flare:dev
            ```
        run: |
          # Create new tag
          git tag -f development
          # Force push the tag
          git push origin development --force
          # Create new dev release
          gh release create development \
            --title "Development Build" \
            --notes "$RELEASE_NOTES" \
            --target dev \
            --prerelease 