name: Release

on:
  push:
    tags:
      - 'v*'

env:
  DOCKERHUB_REGISTRY: docker.io
  GHCR_REGISTRY: ghcr.io

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      docker_tags: ${{ steps.meta.outputs.tags }}
      ghcr_tags: ${{ steps.ghcr_meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker Hub
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REGISTRY }}/flintsh/flare
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract metadata for GitHub Container Registry
        id: ghcr_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_REGISTRY }}/flintsh/flare
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker images (multi-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.ghcr_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [docker]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Check if prerelease
        id: check_prerelease
        run: |
          if [[ "${{ steps.get_version.outputs.VERSION }}" == *-pre* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Get commit messages
        id: get_commits
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            # If no previous tag exists, get all commits
            COMMITS=$(git log --pretty=format:"- %s" --no-merges)
          else
            # Get commits between previous tag and current
            COMMITS=$(git log --pretty=format:"- %s" --no-merges ${PREV_TAG}..HEAD)
          fi
          echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate Release Body
        id: release_body
        run: |
          cat << 'EOF' > release_body.md
          <div align="center">
            <picture>
              <img alt="Flare" src="https://raw.githubusercontent.com/FlintSH/flare/main/public/banner.png" width="600">
            </picture>

            A modern, lightning-fast file sharing platform built for self-hosting
          </div>

          ## 📝 What's Changed

          ${{ steps.get_commits.outputs.COMMITS }}

          ## 📦 Download & Deploy

          ### 🐳 Docker Images
          ```bash
          # Docker Hub
          docker pull docker.io/flintsh/flare:${{ steps.get_version.outputs.VERSION }}

          # GitHub Container Registry
          docker pull ghcr.io/flintsh/flare:${{ steps.get_version.outputs.VERSION }}
          ```

          ### ☁️ Deploy with Railway
          Deploy Flare in a few clicks with its Railway template.

          [![Deploy on Railway](https://railway.app/button.svg)](https://railway.com/template/JVT41u?referralCode=R5s8WT)
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: ${{ steps.check_prerelease.outputs.IS_PRERELEASE }}
          body_path: release_body.md 
